from apps.listings.choices import ListingType
from apps.users.choices import GenderChoices

FAKE_EMAIL_DOMAIN = "fakersdom.example"

FIRST_NAMES = [
    # MALE
    ("Lukas", GenderChoices.MALE),
    ("Finn", GenderChoices.MALE),
    ("Jonas", GenderChoices.MALE),
    ("Paul", GenderChoices.MALE),
    ("Felix", GenderChoices.MALE),
    ("Maximilian", GenderChoices.MALE),
    ("Elias", GenderChoices.MALE),
    ("David", GenderChoices.MALE),
    ("Leon", GenderChoices.MALE),
    ("Ben", GenderChoices.MALE),
    ("Noah", GenderChoices.MALE),
    ("Luis", GenderChoices.MALE),
    ("Jannis", GenderChoices.MALE),
    ("Julian", GenderChoices.MALE),
    ("Niklas", GenderChoices.MALE),
    ("Tim", GenderChoices.MALE),
    ("Jan", GenderChoices.MALE),
    ("Erik", GenderChoices.MALE),
    ("Fabian", GenderChoices.MALE),
    ("Sebastian", GenderChoices.MALE),
    # FEMALE
    ("Anna", GenderChoices.FEMALE),
    ("Lena", GenderChoices.FEMALE),
    ("Marie", GenderChoices.FEMALE),
    ("Sophie", GenderChoices.FEMALE),
    ("Emma", GenderChoices.FEMALE),
    ("Laura", GenderChoices.FEMALE),
    ("Hannah", GenderChoices.FEMALE),
    ("Mia", GenderChoices.FEMALE),
    ("Leonie", GenderChoices.FEMALE),
    ("Lina", GenderChoices.FEMALE),
    ("Mila", GenderChoices.FEMALE),
    ("Emilia", GenderChoices.FEMALE),
    ("Luisa", GenderChoices.FEMALE),
    ("Amelie", GenderChoices.FEMALE),
    ("Johanna", GenderChoices.FEMALE),
    ("Nele", GenderChoices.FEMALE),
    ("Charlotte", GenderChoices.FEMALE),
    ("Clara", GenderChoices.FEMALE),
    ("Larissa", GenderChoices.FEMALE),
    ("Sarah", GenderChoices.FEMALE),
    # OTHER / GENDER-NEUTRAL
    ("Alex", GenderChoices.OTHER),
    ("Robin", GenderChoices.OTHER),
    ("Mika", GenderChoices.OTHER),
    ("Toni", GenderChoices.OTHER),
    ("Kim", GenderChoices.OTHER),
    ("Chris", GenderChoices.OTHER),
    ("Luca", GenderChoices.OTHER),
    ("Jona", GenderChoices.OTHER),
]

LAST_NAMES = [
    "Müller",
    "Schmidt",
    "Schneider",
    "Fischer",
    "Weber",
    "Meyer",
    "Wagner",
    "Becker",
    "Hoffmann",
    "Schäfer",
    "Koch",
    "Richter",
    "Klein",
    "Wolf",
    "Neumann",
    "Schwarz",
    "Zimmermann",
    "Braun",
    "Krüger",
    "Hartmann",
    "Lange",
    "Schulz",
    "Krause",
    "Werner",
    "Köhler",
    "Herrmann",
    "König",
    "Walter",
    "Mayer",
    "Huber",
    "Kaiser",
    "Fuchs",
    "Scholz",
    "Weiß",
    "Lang",
    "Lutz",
    "Meier",
    "Bauer",
    "Schröder",
    "Graf",
    "Vogel",
    "Schubert",
    "Roth",
    "Frank",
    "Winkler",
    "Jäger",
    "Lorenz",
    "Ludwig",
    "Baumann",
    "Heinrich",
    "Vogt",
    "Böhme",
    "Ebert",
    "Thomas",
]

CITIES = [
    ("Berlin", "Berlin", "Mitte"),
    ("Berlin", "Berlin", "Kreuzberg"),
    ("Berlin", "Berlin", "Prenzlauer Berg"),
    ("Berlin", "Berlin", "Charlottenburg"),
    ("München", "Bayern", "Schwabing"),
    ("München", "Bayern", "Maxvorstadt"),
    ("München", "Bayern", "Glockenbachviertel"),
    ("Hamburg", "Hamburg", "Altona"),
    ("Hamburg", "Hamburg", "Eimsbüttel"),
    ("Hamburg", "Hamburg", "St. Pauli"),
    ("Köln", "Nordrhein-Westfalen", "Ehrenfeld"),
    ("Köln", "Nordrhein-Westfalen", "Südstadt"),
    ("Köln", "Nordrhein-Westfalen", "Nippes"),
    ("Frankfurt am Main", "Hessen", "Sachsenhausen"),
    ("Frankfurt am Main", "Hessen", "Nordend"),
    ("Stuttgart", "Baden-Württemberg", "Stuttgart-West"),
    ("Stuttgart", "Baden-Württemberg", "Bad Cannstatt"),
    ("Düsseldorf", "Nordrhein-Westfalen", "Flingern"),
    ("Düsseldorf", "Nordrhein-Westfalen", "Unterbilk"),
    ("Leipzig", "Sachsen", "Plagwitz"),
    ("Leipzig", "Sachsen", "Südvorstadt"),
    ("Dortmund", "Nordrhein-Westfalen", "Kreuzviertel"),
    ("Essen", "Nordrhein-Westfalen", "Rüttenscheid"),
    ("Bremen", "Bremen", "Ostertor"),
    ("Dresden", "Sachsen", "Neustadt"),
    ("Hannover", "Niedersachsen", "List"),
    ("Nürnberg", "Bayern", "Gostenhof"),
    ("Duisburg", "Nordrhein-Westfalen", "Ruhrort"),
    ("Bochum", "Nordrhein-Westfalen", "Ehrenfeld"),
    ("Wuppertal", "Nordrhein-Westfalen", "Elberfeld"),
    ("Bielefeld", "Nordrhein-Westfalen", "Mitte"),
    ("Bonn", "Nordrhein-Westfalen", "Poppelsdorf"),
    ("Münster", "Nordrhein-Westfalen", "Kreuzviertel"),
    ("Karlsruhe", "Baden-Württemberg", None),
    ("Mannheim", "Baden-Württemberg", "Jungbusch"),
    ("Augsburg", "Bayern", None),
    ("Wiesbaden", "Hessen", None),
    ("Gelsenkirchen", "Nordrhein-Westfalen", None),
    ("Mönchengladbach", "Nordrhein-Westfalen", None),
    ("Braunschweig", "Niedersachsen", None),
    ("Chemnitz", "Sachsen", None),
    ("Kiel", "Schleswig-Holstein", None),
    ("Aachen", "Nordrhein-Westfalen", None),
    ("Halle (Saale)", "Sachsen-Anhalt", None),
    ("Magdeburg", "Sachsen-Anhalt", None),
    ("Freiburg im Breisgau", "Baden-Württemberg", None),
    ("Krefeld", "Nordrhein-Westfalen", None),
    ("Mainz", "Rheinland-Pfalz", None),
    ("Lübeck", "Schleswig-Holstein", None),
    ("Erfurt", "Thüringen", None),
    ("Oberhausen", "Nordrhein-Westfalen", None),
    ("Rostock", "Mecklenburg-Vorpommern", None),
    ("Kassel", "Hessen", None),
    ("Hagen", "Nordrhein-Westfalen", None),
    ("Potsdam", "Brandenburg", None),
    ("Saarbrücken", "Saarland", None),
    ("Hamm", "Nordrhein-Westfalen", None),
    ("Ludwigshafen am Rhein", "Rheinland-Pfalz", None),
    ("Mülheim an der Ruhr", "Nordrhein-Westfalen", None),
    ("Oldenburg", "Niedersachsen", None),
    ("Osnabrück", "Niedersachsen", None),
    ("Leverkusen", "Nordrhein-Westfalen", None),
    ("Heidelberg", "Baden-Württemberg", None),
    ("Solingen", "Nordrhein-Westfalen", None),
    ("Darmstadt", "Hessen", None),
    ("Herne", "Nordrhein-Westfalen", None),
    ("Neuss", "Nordrhein-Westfalen", None),
    ("Regensburg", "Bayern", None),
    ("Paderborn", "Nordrhein-Westfalen", None),
    ("Ingolstadt", "Bayern", None),
    ("Offenbach am Main", "Hessen", None),
    ("Würzburg", "Bayern", None),
    ("Fürth", "Bayern", None),
    ("Ulm", "Baden-Württemberg", None),
    ("Heilbronn", "Baden-Württemberg", None),
    ("Pforzheim", "Baden-Württemberg", None),
    ("Wolfsburg", "Niedersachsen", None),
    ("Göttingen", "Niedersachsen", None),
    ("Bottrop", "Nordrhein-Westfalen", None),
    ("Reutlingen", "Baden-Württemberg", None),
    ("Koblenz", "Rheinland-Pfalz", None),
    ("Recklinghausen", "Nordrhein-Westfalen", None),
    ("Bremerhaven", "Bremen", None),
    ("Bergisch Gladbach", "Nordrhein-Westfalen", None),
    ("Jena", "Thüringen", None),
    ("Remscheid", "Nordrhein-Westfalen", None),
    ("Erlangen", "Bayern", None),
    ("Moers", "Nordrhein-Westfalen", None),
    ("Trier", "Rheinland-Pfalz", None),
    ("Siegen", "Nordrhein-Westfalen", None),
    ("Hildesheim", "Niedersachsen", None),
    ("Salzgitter", "Niedersachsen", None),
    ("Cottbus", "Brandenburg", None),
    ("Kaiserslautern", "Rheinland-Pfalz", None),
    ("Gütersloh", "Nordrhein-Westfalen", None),
    ("Schwerin", "Mecklenburg-Vorpommern", None),
    ("Witten", "Nordrhein-Westfalen", None),
    ("Gera", "Thüringen", None),
    ("Iserlohn", "Nordrhein-Westfalen", None),
    ("Ludwigsburg", "Baden-Württemberg", None),
    ("Hanau", "Hessen", None),
    ("Esslingen am Neckar", "Baden-Württemberg", None),
    ("Zwickau", "Sachsen", None),
    ("Düren", "Nordrhein-Westfalen", None),
    ("Ratingen", "Nordrhein-Westfalen", None),
    ("Tübingen", "Baden-Württemberg", None),
    ("Flensburg", "Schleswig-Holstein", None),
    ("Lünen", "Nordrhein-Westfalen", None),
    ("Villingen-Schwenningen", "Baden-Württemberg", None),
    ("Gießen", "Hessen", None),
    ("Marl", "Nordrhein-Westfalen", None),
    ("Dessau-Roßlau", "Sachsen-Anhalt", None),
    ("Konstanz", "Baden-Württemberg", None),
    ("Saarlouis", "Saarland", "Roden"),
    ("Cochem", "Rheinland-Pfalz", "Altstadt"),
    ("Rothenburg ob der Tauber", "Bayern", "Altstadt"),
    ("Görlitz", "Sachsen", "Altstadt"),
    ("Speyer", "Rheinland-Pfalz", None),
    ("Aschaffenburg", "Bayern", None),
]

STREETS = [
    # Hauptstraßen & Boulevards
    "Hauptstraße",
    "Bahnhofstraße",
    "Rathausstraße",
    "Kaiserstraße",
    "Marktstraße",
    "Schlossstraße",
    "Friedrichstraße",
    "Ludwigstraße",
    "Maximilianstraße",
    "Königstraße",
    "Leipziger Straße",
    "Berliner Straße",
    "Frankfurter Straße",
    "Münchner Straße",
    "Hamburger Straße",
    "Kölnische Straße",
    "Goethestraße",
    "Schillerstraße",
    "Lessingstraße",
    "Heineschleife",
    # Natur & Alleen
    "Lindenstraße",
    "Birkenweg",
    "Eichenweg",
    "Buchenweg",
    "Kastanienallee",
    "Kiefernweg",
    "Ahornweg",
    "Weidenweg",
    "Gartenstraße",
    "Parkstraße",
    "Am Stadtpark",
    "Blumenstraße",
    "Rosenweg",
    "Tulpenweg",
    "Waldstraße",
    "Forstweg",
    "Bergstraße",
    "Talstraße",
    "Am Hang",
    "Wiesenweg",
    # Plätze
    "Marktplatz",
    "Rathausplatz",
    "Bahnhofsplatz",
    "Kirchplatz",
    "Schlossplatz",
    "Alexanderplatz",
    "Marienplatz",
    "Münsterplatz",
    "Domplatz",
    "Theaterplatz",
    "Opernplatz",
    "Schillerplatz",
    "Goetheplatz",
    "Augustusplatz",
    "Pariser Platz",
    "Karlsplatz",
    # Ufer & Brücken
    "Rheinstraße",
    "Donauweg",
    "Elbchaussee",
    "Uferstraße",
    "Am Flussufer",
    "Hafenstraße",
    "An der Werft",
    "Brückenstraße",
    "Kanalstraße",
    "Inselstraße",
    "Seeweg",
    "Fischerufer",
    # Altstadt, Gassen & Wälle
    "Burgstraße",
    "Wallstraße",
    "Grabenstraße",
    "Mühlenstraße",
    "Poststraße",
    "Kirchgasse",
    "Schmiedegasse",
    "Bäckergasse",
    "Fleischergasse",
    "Herrengasse",
    "Pfarrgasse",
    "Klosterstraße",
    "Kreuzstraße",
    "Jakobsweg",
    "Alte Gasse",
    "Hinterm Wall",
]

LISTING_ADJECTIVES = [
    "Gemütliche",
    "Helle",
    "Moderne",
    "Stilvolle",
    "Ruhige",
    "Zentrale",
    "Schicke",
    "Exklusive",
    "Charmante",
    "Lichtdurchflutete",
    "Einladende",
    "Idyllische",
    "Komfortable",
    "Sonnige",
    "Gepflegte",
    "Preiswerte",
]

LISTING_FEATURES = [
    "mit Balkon",
    "nahe Bahnhof",
    "mit Garten",
    "in Innenstadtlage",
    "mit Domblick",
    "nahe Altstadt",
    "mit Terrasse",
    "in ruhiger Seitenstraße",
    "mit WLAN & Netflix",
    "für Familien",
    "mit Parkplatz",
    "nahe Messe",
    "mit Traumblick",
    "im Szeneviertel",
    "nahe ÖPNV",
    "mit Fußbodenheizung",
]

LISTING_TITLES_BASE = {
    ListingType.APARTMENT: [
        "Wohnung",
        "Altbauwohnung",
        "Apartment",
        "Loft",
        "Studio",
        "Ferienwohnung",
        "Unterkunft",
        "Penthouse",
        "City-Wohnung",
    ],
    ListingType.HOTEL: [
        "Boutique-Hotel",
        "Familienhotel",
        "Business-Hotel",
        "Komforthotel",
        "Design-Hotel",
        "Wellness-Hotel",
        "Stadthotel",
        "Traditionshotel",
    ],
    ListingType.HOSTEL: [
        "Backpacker-Hostel",
        "City-Hostel",
        "Jugendherberge",
        "Design-Hostel",
        "Budget-Hostel",
        "Eco-Hostel",
        "Kultur-Hostel",
        "Zentral-Hostel",
    ],
}

REVIEW_COMMENTS_POSITIVE = [
    "Wirklich toller Aufenthalt, alles hat gepasst und die Lage war super.",
    "Sehr sauber, freundlicher Gastgeber, jederzeit wieder!",
    "Genau wie auf den Fotos beschrieben, kann ich nur empfehlen.",
    "Tolle Ausstattung und schnelle Kommunikation mit dem Vermieter.",
    "Wunderschöne Unterkunft! Sehr geschmackvoll eingerichtet und blitzsauber.",
    "Die Lage ist unschlagbar, man ist super schnell an allen wichtigen Punkten.",
    "Haben uns ab der ersten Minute wie zu Hause gefühlt. Perfekt für ein langes Wochenende!",
    "Sehr gemütliche Betten und eine top ausgestattete Küche. Es hat an nichts gefehlt.",
    "Der Ausblick war einfach traumhaft! Allein dafür hat sich der Aufenthalt gelohnt.",
    "Sehr unkomplizierter Check-in und ein extrem aufmerksamer Gastgeber.",
    "Ein echtes Juwel! Ruhige Lage, aber dennoch sehr zentral. Gerne wieder!",
    "Modernes Design, stabiles WLAN (wichtig fürs Homeoffice) und alles sehr gepflegt.",
    "Hervorragendes Preis-Leistungs-Verhältnis. Kann diese Unterkunft wärmstens empfehlen.",
    "Alles war perfekt vorbereitet. Danke für die tollen Tipps für Restaurants in der Umgebung!",
    "Super gemütlich, sauber und ein sehr bequemes Einchecken per Schlüsselbox.",
]

REVIEW_COMMENTS_MIXED = [
    "Insgesamt okay, aber die Anreise war etwas kompliziert zu finden.",
    "Nette Unterkunft, allerdings etwas laut zur Straße hin.",
    "Gutes Preis-Leistungs-Verhältnis, kleine Mängel bei der Ausstattung.",
    "Die Wohnung ist schön, aber das WLAN war leider sehr langsam und instabil.",
    "Gute Lage und netter Kontakt, aber die Sauberkeit im Badezimmer hätte besser sein können.",
    "Für eine Nacht absolut ausreichend, für einen längeren Aufenthalt wäre es mir zu eng.",
    "Schick eingerichtet, aber die Matratze war leider viel zu weich für meinen Geschmack.",
    "Der Aufenthalt war okay, allerdings riecht es im Flur etwas muffig.",
    "Schöne Aussicht, aber die Parkplatzsuche in der Umgebung war eine absolute Katastrophe.",
    "Die Kommunikation war super, aber die Möbel in der Küche sind schon etwas in die Jahre gekommen.",
    "Zentrale Lage, aber der Wasserdruck in der Dusche war leider sehr schwach.",
    "Die Unterkunft war sauber, aber auf den Fotos wirkte alles deutlich größer.",
    "Übergabe lief problemlos, aber nachts hat man die Nachbarn recht deutlich gehört.",
    "Alles Notwendige war da, aber der Check-in hat sich um fast eine Stunde verzögert.",
    "Es war sauber und ordentlich, aber das Preis-Leistungs-Verhältnis stimmt hier nicht ganz.",
]
