# Generated by Django 6.0.6 on 2026-07-13 06:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Price",
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "valid_from",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Valid from"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.room",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from", "-created_at"],
                "indexes": [
                    models.Index(fields=["valid_from"], name="idx_price_date"),
                    models.Index(
                        fields=["listing", "valid_from"], name="idx_listing_price_date"
                    ),
                    models.Index(
                        fields=["room", "valid_from"], name="idx_room_price_date"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("listing__isnull", False), ("room__isnull", True)
                            ),
                            models.Q(
                                ("listing__isnull", True), ("room__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="price_history_xor_listing_or_room",
                    )
                ],
            },
        ),
    ]
