# Generated by Django 6.0.6 on 2026-07-10 10:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0002_alter_listing_price_per_night"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.room",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["effective_date"], name="idx_price_date"),
                    models.Index(
                        fields=["listing", "effective_date"],
                        name="idx_listing_price_date",
                    ),
                    models.Index(
                        fields=["room", "effective_date"], name="idx_room_price_date"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("listing__isnull", False), ("room__isnull", True)
                            ),
                            models.Q(
                                ("listing__isnull", True), ("room__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="price_history_xor_listing_or_room",
                    )
                ],
                "unique_together": {("listing", "room", "effective_date")},
            },
        ),
    ]
