GROUP_TENANT = "tenant"
GROUP_LANDLORD = "landlord"
GROUP_MODERATOR = "moderator"
GROUP_ADMIN = "admin"

SYSTEM_ROLES = [
    GROUP_TENANT,
    GROUP_LANDLORD,
    GROUP_MODERATOR,
    GROUP_ADMIN,
]
