from apps.bookings.choices import DisputeStatus

MAX_BOOKING_DURATION_DAYS = 365
DAILY_RENTAL_MAX_DAYS = 60
LONG_TERM_MIN_DAYS = 60

TENANT_FREE_CANCEL_CUTOFF_HOURS = 24

AUTO_CANCEL_TIMEOUT_MINUTES = 30
BUSINESS_HOURS_START = 9
BUSINESS_HOURS_END = 21

DISPUTE_OPEN_WINDOW_DAYS = 3
REVIEW_WINDOW_DAYS = 7

DISPUTE_ALLOWED_TRANSITIONS = {
    DisputeStatus.OPEN: {DisputeStatus.UNDER_REVIEW},
    DisputeStatus.UNDER_REVIEW: {
        DisputeStatus.RESOLVED_REFUNDED,
        DisputeStatus.RESOLVED_REJECTED,
    },
    DisputeStatus.RESOLVED_REFUNDED: set(),
    DisputeStatus.RESOLVED_REJECTED: set(),
}

LAST_MINUTE_DISCOUNT_SAME_DAY = 0.15
LAST_MINUTE_DISCOUNT_NEXT_DAY = 0.10
