# Generated by Django 6.0.6 on 2026-07-10 10:24

import apps.content.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0002_alter_listing_price_per_night"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(upload_to=apps.content.models.photo_upload_path),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.room",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["listing"], name="idx_photo_listing"),
                    models.Index(fields=["room"], name="idx_photo_room"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("listing__isnull", False), ("room__isnull", True)
                            ),
                            models.Q(
                                ("listing__isnull", True), ("room__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="photo_xor_listing_or_room",
                    )
                ],
            },
        ),
    ]
