# Generated by Django 6.0.6 on 2026-07-07 18:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Surname"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Contact phone",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Employee status"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="Superuser status"),
                ),
                (
                    "token_version",
                    models.IntegerField(default=1, verbose_name="Token version"),
                ),
                (
                    "blocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Blocking date"
                    ),
                ),
                (
                    "blocked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SPAM", "Spam and advertising"),
                            ("FRAUD", "Fraud"),
                            ("TOS_VIOLATION", "Violation of Terms of Use (ToS)"),
                            ("FAKE_LISTING", "Fake or fraudulent advertisement"),
                            ("ABUSE", "Insults, aggression, or inappropriate behavior"),
                            ("OTHER", "Another reason"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Reason for blocking",
                    ),
                ),
                (
                    "notify_by_email",
                    models.BooleanField(
                        default=True, verbose_name="Email notifications"
                    ),
                ),
                (
                    "terms_accepted_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date of adoption of the agreement",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Registration date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last updated"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Logical deletion date"
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Blocked by whom",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
        ),
    ]
