# Generated by Django 6.0.6 on 2026-07-08 17:57

import core.validators
import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth date"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Blocked status"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[core.validators.validate_image],
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The phone number must be in E.164 format (starting with the + sign and country code, 7 to 15 characters).",
                        regex="^\\+[1-9]\\d{6,14}$",
                    )
                ],
                verbose_name="Contact phone",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[core.validators.validate_custom_email],
                verbose_name="Email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The field may contain only letters (including umlauts), spaces, hyphens, and apostrophes.",
                        regex="^[A-Za-zÀ-ÖØ-öø-ÿ\\s\\-']+$",
                    )
                ],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The field may contain only letters (including umlauts), spaces, hyphens, and apostrophes.",
                        regex="^[A-Za-zÀ-ÖØ-öø-ÿ\\s\\-']+$",
                    )
                ],
                verbose_name="Surname",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The username must be between 3 and 30 characters long and consist only of Latin letters, numbers, and '_'.",
                        regex="^[A-Za-z0-9_]{3,30}$",
                    )
                ],
                verbose_name="Username",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The phone number must be in E.164 format (starting with the + sign and country code, 7 to 15 characters).",
                        regex="^\\+[1-9]\\d{6,14}$",
                    )
                ],
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="token_version",
            field=models.PositiveIntegerField(default=0, verbose_name="Token version"),
        ),
    ]
