# Generated by Django 6.0.6 on 2026-07-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("X", "Other")],
                help_text="Optional field. M – Male, F – Female, X – Other.",
                max_length=1,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
