# Generated by Django 6.0.6 on 2026-07-13 06:53

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("wifi", "Free Wi-Fi"),
                            ("air_conditioning", "Air Conditioning"),
                            ("heating", "Heating"),
                            ("iron", "Iron"),
                            ("dedicated_workspace", "Dedicated Workspace"),
                            ("kitchen", "Fully Equipped Kitchen"),
                            ("refrigerator", "Refrigerator"),
                            ("microwave", "Microwave"),
                            ("coffee_maker", "Coffee Maker"),
                            ("tv", "TV / Cable"),
                            ("sound_system", "Sound System"),
                            ("free_parking", "Free Parking on Premises"),
                            ("swimming_pool", "Swimming Pool"),
                            ("gym", "Gym / Fitness Center"),
                            ("washing_machine", "Washing Machine"),
                            ("elevator", "Elevator"),
                            ("balcony", "Balcony / Terrace"),
                            ("bbq_grill", "BBQ Grill"),
                            ("beach_front", "Beachfront Access"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="System Key",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic", "Basic Utilities"),
                            ("kitchen", "Kitchen & Dining"),
                            ("media", "Media & Technology"),
                            ("services", "Facilities & Services"),
                            ("outdoors", "Outdoors & Views"),
                        ],
                        default="basic",
                        max_length=50,
                        verbose_name="Category Group",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Icon Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.CharField(
                        default="Germany", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        max_length=100, verbose_name="Region (Bundesland)"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="District"
                    ),
                ),
                ("street", models.CharField(max_length=255, verbose_name="Street")),
                (
                    "house_number",
                    models.CharField(max_length=20, verbose_name="House Number"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Postal Code"),
                ),
                (
                    "floor",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Floor"
                    ),
                ),
                (
                    "apartment_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Apartment Number",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90.0")),
                            django.core.validators.MaxValueValidator(Decimal("90.0")),
                        ],
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180.0")),
                            django.core.validators.MaxValueValidator(Decimal("180.0")),
                        ],
                        verbose_name="Longitude",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__isnull", True),
                            models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                            _connector="OR",
                        ),
                        name="address_latitude_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__isnull", True),
                            models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                            _connector="OR",
                        ),
                        name="address_longitude_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in_time",
                    models.TimeField(
                        default=datetime.time(14, 0), verbose_name="Check-in time"
                    ),
                ),
                (
                    "check_out_time",
                    models.TimeField(
                        default=datetime.time(11, 0), verbose_name="Check-out time"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("hotel", "Hotel"),
                            ("hostel", "Hostel"),
                        ],
                        default="apartment",
                        max_length=20,
                        verbose_name="Property Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maximum Guests",
                    ),
                ),
                (
                    "rooms_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Used for type=apartment; not applicable to hotel/hostel.",
                        null=True,
                        verbose_name="Rooms Count",
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Current Price (cached from PriceHistory)",
                    ),
                ),
                (
                    "rental_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("long_term", "Long Term"),
                            ("any", "Any Type"),
                        ],
                        default="any",
                        max_length=20,
                        verbose_name="Rental Type",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("none", "No Meals"),
                            ("breakfast", "Breakfast Included"),
                            ("half_board", "Half Board"),
                            ("full_board", "Full Board"),
                            ("all_inclusive", "All Inclusive"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Meal Type",
                    ),
                ),
                (
                    "deposit_required",
                    models.BooleanField(default=False, verbose_name="Deposit Required"),
                ),
                (
                    "deposit_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Deposit Percent",
                    ),
                ),
                (
                    "deposit_refundable",
                    models.BooleanField(
                        default=False, verbose_name="Deposit Refundable"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Views Count"),
                ),
                (
                    "rating_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Denormalized, recalculated by signal on Review change.",
                        max_digits=3,
                        verbose_name="Average Rating",
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Denormalized, recalculated by signal on Review change.",
                        verbose_name="Reviews Count",
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listing",
                        to="listings.address",
                        verbose_name="Address",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ListingAmenity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_listings",
                        to="listings.amenity",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_amenities",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Amenity",
                "verbose_name_plural": "Listing Amenities",
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                related_name="listings",
                through="listings.ListingAmenity",
                to="listings.amenity",
                verbose_name="Amenities",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in_time",
                    models.TimeField(
                        default=datetime.time(14, 0), verbose_name="Check-in time"
                    ),
                ),
                (
                    "check_out_time",
                    models.TimeField(
                        default=datetime.time(11, 0), verbose_name="Check-out time"
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Room"),
                            ("double", "Double Room"),
                            ("twin", "Twin Room"),
                            ("triple", "Triple Room"),
                            ("quad", "Quadruple Room"),
                            ("suite", "Suite"),
                            ("studio", "Studio Room"),
                            ("dorm_bed", "Bed in Dormitory Room"),
                            ("family", "Family Room"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="Room Type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Room Name/Number"
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maximum Guests",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="listings.listing",
                        verbose_name="Listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="listingamenity",
            constraint=models.UniqueConstraint(
                fields=("listing", "amenity"), name="unique_listing_amenity"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-views_count"], name="listings_li_views_c_7f0dc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-reviews_count"], name="listings_li_reviews_3bfa30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["type", "status", "is_active"],
                name="listings_li_type_7f0121_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_guests__gte", 1)),
                name="listing_max_guests_minimum",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deposit_percent__gte", 0), ("deposit_percent__lte", 100)
                ),
                name="listing_deposit_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_guests__gte", 1)),
                name="room_max_guests_minimum",
            ),
        ),
    ]
