# Generated by Django 6.0.6 on 2026-07-09 20:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("wifi", "Free Wi-Fi"),
                            ("air_conditioning", "Air Conditioning"),
                            ("heating", "Heating"),
                            ("iron", "Iron"),
                            ("dedicated_workspace", "Dedicated Workspace"),
                            ("kitchen", "Fully Equipped Kitchen"),
                            ("refrigerator", "Refrigerator"),
                            ("microwave", "Microwave"),
                            ("coffee_maker", "Coffee Maker"),
                            ("tv", "TV / Cable"),
                            ("sound_system", "Sound System"),
                            ("free_parking", "Free Parking on Premises"),
                            ("swimming_pool", "Swimming Pool"),
                            ("gym", "Gym / Fitness Center"),
                            ("washing_machine", "Washing Machine"),
                            ("elevator", "Elevator"),
                            ("balcony", "Balcony / Terrace"),
                            ("bbq_grill", "BBQ Grill"),
                            ("beach_front", "Beachfront Access"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="System Key",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic", "Basic Utilities"),
                            ("kitchen", "Kitchen & Dining"),
                            ("media", "Media & Technology"),
                            ("services", "Facilities & Services"),
                            ("outdoors", "Outdoors & Views"),
                        ],
                        default="basic",
                        max_length=50,
                        verbose_name="Category Group",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Icon Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("hotel", "Hotel"),
                            ("hostel", "Hostel"),
                        ],
                        default="apartment",
                        max_length=20,
                        verbose_name="Property Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90.0")),
                            django.core.validators.MaxValueValidator(Decimal("90.0")),
                        ],
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180.0")),
                            django.core.validators.MaxValueValidator(Decimal("180.0")),
                        ],
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maximum Guests",
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price Per Night"
                    ),
                ),
                (
                    "rental_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("long_term", "Long Term"),
                            ("any", "Any Type"),
                        ],
                        default="any",
                        max_length=20,
                        verbose_name="Rental Type",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("none", "No Meals"),
                            ("breakfast", "Breakfast Included"),
                            ("half_board", "Half Board"),
                            ("full_board", "Full Board"),
                            ("all_inclusive", "All Inclusive"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Meal Type",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="listings",
                        to="listings.amenity",
                        verbose_name="Amenities",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Room"),
                            ("double", "Double Room"),
                            ("twin", "Twin Room"),
                            ("triple", "Triple Room"),
                            ("quad", "Quadruple Room"),
                            ("suite", "Suite"),
                            ("studio", "Studio Room"),
                            ("dorm_bed", "Bed in Dormitory Room"),
                            ("family", "Family Room"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="Room Type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Room Name/Number"
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maximum Guests",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="listings.listing",
                        verbose_name="Listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="listing_latitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="listing_longitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_guests__gte", 1)),
                name="listing_max_guests_minimum",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_guests__gte", 1)),
                name="room_max_guests_minimum",
            ),
        ),
    ]
