# Generated by Django 6.0.6 on 2026-07-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("wifi", "Free Wi-Fi"),
                            ("air_conditioning", "Air Conditioning"),
                            ("heating", "Heating"),
                            ("iron", "Iron"),
                            ("dedicated_workspace", "Dedicated Workspace"),
                            ("kitchen", "Fully Equipped Kitchen"),
                            ("refrigerator", "Refrigerator"),
                            ("microwave", "Microwave"),
                            ("coffee_maker", "Coffee Maker"),
                            ("tv", "TV / Cable"),
                            ("sound_system", "Sound System"),
                            ("free_parking", "Free Parking on Premises"),
                            ("swimming_pool", "Swimming Pool"),
                            ("gym", "Gym / Fitness Center"),
                            ("washing_machine", "Washing Machine"),
                            ("elevator", "Elevator"),
                            ("balcony", "Balcony / Terrace"),
                            ("bbq_grill", "BBQ Grill"),
                            ("beach_front", "Beachfront Access"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="System Key",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Utilities"),
                            ("kitchen", "Kitchen & Dining"),
                            ("media", "Media & Technology"),
                            ("services", "Facilities & Services"),
                            ("outdoors", "Outdoors & Views"),
                        ],
                        default="basic",
                        max_length=50,
                        verbose_name="Category Group",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Icon Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="listings",
                        to="listings.amenity",
                        verbose_name="Amenities",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
            },
        ),
    ]
