# Generated by Django 6.0.6 on 2026-07-16 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="rooms_available_count",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="Available rooms of this category",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="max_guests",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 Guest"),
                    (2, "2 Guests"),
                    (3, "3 Guests"),
                    (4, "4 Guests"),
                    (5, "5 Guests"),
                    (6, "6 Guests"),
                    (7, "7 Guests"),
                    (8, "8 Guests"),
                    (10, "10 Guests"),
                    (12, "12 Guests"),
                    (16, "16+ Guests"),
                ],
                verbose_name="Maximum Guests",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="max_guests",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 Guest"),
                    (2, "2 Guests"),
                    (3, "3 Guests"),
                    (4, "4 Guests"),
                    (5, "5 Guests"),
                    (6, "6 Guests"),
                    (7, "7 Guests"),
                    (8, "8 Guests"),
                    (10, "10 Guests"),
                    (12, "12 Guests"),
                    (16, "16+ Guests"),
                ],
                verbose_name="Maximum Guests",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(("rooms_available_count__gte", 1)),
                name="room_available_count_minimum",
            ),
        ),
    ]
