# Generated by Django 6.0.6 on 2026-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basic", "Basic Utilities"),
                    ("kitchen", "Kitchen & Dining"),
                    ("media", "Media & Technology"),
                    ("services", "Facilities & Services"),
                    ("outdoors", "Outdoors & Views"),
                ],
                default="basic",
                max_length=50,
                verbose_name="Category Group",
            ),
        ),
    ]
