# Generated by Django 6.0.6 on 2026-07-10 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listing_price_per_night"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="check_in_time",
            field=models.TimeField(
                default=datetime.time(14, 0), verbose_name="Check-in time"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="check_out_time",
            field=models.TimeField(
                default=datetime.time(11, 0), verbose_name="Check-out time"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="check_in_time",
            field=models.TimeField(
                default=datetime.time(14, 0), verbose_name="Check-in time"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="check_out_time",
            field=models.TimeField(
                default=datetime.time(11, 0), verbose_name="Check-out time"
            ),
        ),
    ]
