# Generated by Django 6.0.6 on 2026-07-29 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listing_options_room_rooms_available_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="slug",
            field=models.CharField(
                help_text="Free-form unique key (e.g. 'sauna'). StandardAmenity only seeds the initial well-known set — it does not restrict new values.",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The slug may contain only lowercase Latin letters, digits, and underscores.",
                        regex="^[a-z0-9_]+$",
                    )
                ],
                verbose_name="System Key",
            ),
        ),
    ]
