# Generated by Django 6.0.6 on 2026-08-03 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_amenity_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="slug",
            field=models.CharField(
                help_text="Free-form system key, lowercase snake_case. StandardAmenity is only the source of default seed data (see apps/listings/signals.py), not a closed set — new amenities are not restricted to it.",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Slug must be lowercase snake_case: start with a letter, only lowercase letters, digits and underscores.",
                        regex="^[a-z][a-z0-9_]*$",
                    )
                ],
                verbose_name="System Key",
            ),
        ),
    ]
