# Generated by Django 6.0.6 on 2026-07-13 06:53

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationReason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("personal_emergency", "Personal emergency"),
                            ("changed_plans", "Changed plans"),
                            ("property_unavailable", "Property unavailable"),
                            ("cleanliness_issues", "Cleanliness issues"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Cancellation Reason",
                "verbose_name_plural": "Cancellation Reasons",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected by Landlord"),
                            ("cancelled_by_tenant", "Cancelled by Tenant"),
                            ("cancelled_by_landlord", "Cancelled by Landlord"),
                            ("auto_cancelled", "System Auto-Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="Check-in date")),
                ("check_out_date", models.DateField(verbose_name="Check-out date")),
                (
                    "guests_count",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Guests count",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deposit_refunded",
                    models.BooleanField(default=False, verbose_name="Deposit refunded"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed at"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled at"
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelled by",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.room",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="bookings.cancellationreason",
                        verbose_name="Cancellation reason",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("CLEANLINESS", "Cleanliness issues"),
                            ("AMENITIES_MISSING", "Amenities not available"),
                            ("DAMAGED_PROPERTY", "Property damage"),
                            ("ACCESS_ISSUES", "Access/Check-in issues"),
                            ("MISDESCRIPTION", "Listing misdescription"),
                            ("UNAUTHORIZED_CHARGES", "Unauthorized charges"),
                            ("EARLY_CHECK_OUT", "Early check-out request"),
                            ("CANCELLATION_DISPUTE", "Cancellation dispute"),
                            ("NOISE_COMPLAINT", "Noise complaint"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Detailed description of the issue"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Dispute Opened"),
                            ("under_review", "Under Review by Moderator"),
                            ("resolved_refunded", "Resolved with Full/Partial Refund"),
                            ("resolved_rejected", "Resolved - Claim Rejected"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                (
                    "claim_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Claim amount",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The amount actually awarded may be less than the claim_amount.",
                        max_digits=12,
                        null=True,
                        verbose_name="Resolution amount",
                    ),
                ),
                (
                    "resolution_favor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tenant", "In favor of tenant"),
                            ("landlord", "In favor of landlord"),
                            ("split", "Split between both parties"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Resolution favors",
                    ),
                ),
                (
                    "moderator_notes",
                    models.TextField(blank=True, verbose_name="Moderator notes"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="bookings.booking",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opened_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_disputes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved by",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField(verbose_name="Evidence URL")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="bookings.dispute",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispute_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute Evidence",
                "verbose_name_plural": "Dispute Evidence",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in_date", "check_out_date"],
                name="bookings_bo_check_i_64cf26_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_out_date__gt", models.F("check_in_date"))),
                name="booking_check_out_after_check_in",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_price__gte", 0)),
                name="booking_total_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("listing__isnull", False), ("room__isnull", True)),
                    models.Q(("listing__isnull", True), ("room__isnull", False)),
                    _connector="OR",
                ),
                name="booking_xor_listing_or_room",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["booking", "status"], name="bookings_di_booking_e0666e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.CheckConstraint(
                condition=models.Q(("claim_amount__gte", 0)),
                name="dispute_claim_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "open"),
                    ("status", "under_review"),
                    models.Q(
                        ("status__in", ["resolved_refunded", "resolved_rejected"]),
                        ("resolved_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="dispute_resolution_date_required",
            ),
        ),
    ]
