# Generated by Django 6.0.6 on 2026-07-10 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0003_listing_check_in_time_listing_check_out_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected by Landlord"),
                            ("cancelled_by_tenant", "Cancelled by Tenant"),
                            ("cancelled_by_landlord", "Cancelled by Landlord"),
                            ("auto_cancelled", "System Auto-Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("check_in_at", models.DateTimeField(verbose_name="Check-in time")),
                ("check_out_at", models.DateTimeField(verbose_name="Check-out time")),
                ("guests_count", models.PositiveIntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("personal_emergency", "Personal emergency"),
                            ("changed_plans", "Changed plans"),
                            ("property_unavailable", "Property unavailable"),
                            ("cleanliness_issues", "Cleanliness issues"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Dispute Opened"),
                            ("under_review", "Under Review by Moderator"),
                            ("resolved_refunded", "Resolved with Full/Partial Refund"),
                            ("resolved_rejected", "Resolved - Claim Rejected"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("evidence_url", models.URLField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in_at", "check_out_at"],
                name="bookings_bo_check_i_b465af_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_out_at__gt", models.F("check_in_at"))),
                name="booking_check_out_after_check_in",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_price__gte", 0)),
                name="booking_total_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("listing__isnull", False), ("room__isnull", True)),
                    models.Q(("listing__isnull", True), ("room__isnull", False)),
                    _connector="OR",
                ),
                name="booking_xor_listing_or_room",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["booking", "status"], name="bookings_di_booking_e0666e_idx"
            ),
        ),
    ]
