# Generated by Django 6.0.6 on 2026-07-10 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispute",
            name="description",
        ),
        migrations.AddField(
            model_name="dispute",
            name="claim_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dispute",
            name="opened_by",
            field=models.ForeignKey(
                default="8658e4b5b58049318a9a3496c3fed6e6",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opened_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dispute",
            name="reason",
            field=models.TextField(
                default="No reason provided",
                help_text="Detailed description of the issue",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dispute",
            name="reason_category",
            field=models.CharField(
                choices=[
                    ("CLEANLINESS", "Cleanliness issues"),
                    ("AMENITIES_MISSING", "Amenities not available"),
                    ("DAMAGED_PROPERTY", "Property damage"),
                    ("ACCESS_ISSUES", "Access/Check-in issues"),
                    ("MISDESCRIPTION", "Listing misdescription"),
                    ("UNAUTHORIZED_CHARGES", "Unauthorized charges"),
                    ("EARLY_CHECK_OUT", "Early check-out request"),
                    ("CANCELLATION_DISPUTE", "Cancellation dispute"),
                    ("NOISE_COMPLAINT", "Noise complaint"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispute",
                to="bookings.booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.CheckConstraint(
                condition=models.Q(("claim_amount__gte", 0)),
                name="dispute_claim_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["resolved_refunded", "resolved_rejected"]),
                        ("resolved_at__isnull", False),
                    ),
                    ("status", "open"),
                    _connector="OR",
                ),
                name="dispute_resolution_date_required",
            ),
        ),
    ]
