# Generated by Django 6.0.6 on 2026-07-29 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancellationreason",
            name="code",
            field=models.CharField(
                help_text="Free-form unique code (^[A-Z_]+$). StandardCancellationReason only seeds the initial set.",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The code may contain only uppercase Latin letters and underscores.",
                        regex="^[A-Z_]+$",
                    )
                ],
                verbose_name="Code",
            ),
        ),
    ]
