# Generated by Django 6.0.6 on 2026-08-03 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_cancellationreason_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancellationreason",
            name="code",
            field=models.CharField(
                help_text="Free-form code, ^[A-Z_]+$. StandardCancellationReason is only the source of default seed data (see apps/bookings/signals.py), not a closed set — new reasons are not restricted to it.",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Code must contain only uppercase letters and underscores.",
                        regex="^[A-Z_]+$",
                    )
                ],
                verbose_name="Code",
            ),
        ),
    ]
