# Generated by Django 6.0.6 on 2026-07-13 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("keyword", models.CharField(max_length=255, verbose_name="Keyword")),
                (
                    "results_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of listings matched by this query.",
                        null=True,
                        verbose_name="Results Count",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for unauthenticated guest search.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search History",
                "indexes": [
                    models.Index(
                        fields=["keyword"], name="analytics_s_keyword_5035a3_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analytics_s_user_id_adadb1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ViewHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Django session id, used for guest view dedup instead of IP.",
                        max_length=40,
                        null=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to="listings.listing",
                        verbose_name="Listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for unauthenticated guest view.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="view_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "View History",
                "verbose_name_plural": "View History",
                "indexes": [
                    models.Index(
                        fields=["listing", "created_at"],
                        name="analytics_v_listing_07681d_idx",
                    ),
                    models.Index(
                        fields=["listing", "user", "session_key"],
                        name="analytics_v_listing_921cf9_idx",
                    ),
                ],
            },
        ),
    ]
