# Generated by Django 6.0.6 on 2026-07-13 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "User Registration Success"),
                            ("BOOKING_CONFIRMED", "Booking Confirmed"),
                            ("BOOKING_REJECTED", "Booking Rejected"),
                            ("BOOKING_CANCELLED", "Booking Cancelled"),
                            ("BOOKING_AUTO_CANCELLED", "Booking Auto-Cancelled"),
                            ("PRICE_CHANGED", "Listing Price Changed"),
                            ("NEW_REVIEW", "New Guest Review Received"),
                            ("REVIEW_RESPONSE", "Landlord Response to Review"),
                        ],
                        max_length=30,
                        verbose_name="Notification type",
                    ),
                ),
                ("success", models.BooleanField(verbose_name="Success")),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        help_text="Only populated when success is False.",
                        max_length=500,
                        null=True,
                        verbose_name="Error message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable for system notifications without a specific recipient.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_57d53d_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_be328b_idx",
                    ),
                ],
            },
        ),
    ]
